# Generated by Django 3.2.3 on 2021-05-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Registration',
        ),
    ]
